Basic file check for darwin builds

diff --git a/.github/workflows/release-build.yml b/.github/workflows/release-build.yml
--- a/.github/workflows/release-build.yml
+++ b/.github/workflows/release-build.yml
@@ -30,10 +30,6 @@ jobs:
       - name: Create archive
         run: |
           tar -zcvf golp_linux_${{ matrix.arch }}.tar.gz golp README.md LICENSE
-      - uses: craicoverflow/install-git-chglog@v1
-      - name: git-chglog
-        id: chglog
-        run: echo "::set-output name=changelog::$(git-chglog -t .chglog/RELEASE.tpl.md ${{ steps.tag.outputs.tag }})"
       - name: Upload archive to release
         uses: svenstaro/upload-release-action@v2
         with:
@@ -42,35 +38,7 @@ jobs:
           asset_name: golp_linux_${{ matrix.arch }}.tar.gz
           overwrite: true
           tag: ${{ github.ref }}
-          body: ${{ steps.chglog.outputs.changelog }}
-
-  # linux:
-  #   strategy:
-  #     matrix:
-  #       go-version: [1.18.x]
-  #       os: [ubuntu-latest]
-  #       goarch: ["386", amd64, arm64]
-  #   runs-on: ${{ matrix.os }}
-  #   steps:
-  #   - uses: actions/setup-go@v3
-  #     with:
-  #       go-version: ${{ matrix.go-version }}
-  #   - name: Get tag
-  #     id: tag
-  #     uses: dawidd6/action-get-tag@v1
-  #   - uses: actions/checkout@v3
-  #   - run: go build -ldflags '-s -w -X "github.com/axllent/golp/cmd.Version=${{ steps.tag.outputs.tag }}"'
-  #     env:
-  #       CGO_ENABLED: 1
-  #   - run: tar -zcvf golp_linux_${{ matrix.goarch }}.tar.gz golp README.md LICENSE
-  #   - name: Upload binaries to release
-  #     uses: svenstaro/upload-release-action@v2
-  #     with:
-  #       repo_token: ${{ secrets.GITHUB_TOKEN }}
-  #       file: golp_linux_${{ matrix.goarch }}.tar.gz
-  #       asset_name: golp_linux_${{ matrix.goarch }}.tar.gz
-  #       overwrite: true
-  #       tag: ${{ github.ref }}
+          body: See [CHANGELOG](https://github.com/axllent/golp/blob/develop/CHANGELOG.md)
 
   darwin:
     strategy:
@@ -91,7 +59,15 @@ jobs:
       env:
         CGO_ENABLED: 1
     - run: ./golp version
-    - run: tar -zcvf golp_darwin_${{ matrix.goarch }}.tar.gz golp README.md LICENSE
+    - name: Compress and check size
+      shell: bash
+      run: |
+        tar -zcvf golp_darwin_${{ matrix.goarch }}.tar.gz golp README.md LICENSE
+        SIZE=$(stat -c %s golp_darwin_${{ matrix.goarch }}.tar.gz)
+        if (( $SIZE < 3500000)) ; then
+          echo "File is too small, build failed!"
+          exit 1
+        fi
     - name: Upload binaries to release
       uses: svenstaro/upload-release-action@v2
       with:
@@ -100,7 +76,6 @@ jobs:
         asset_name: golp_darwin_${{ matrix.goarch }}.tar.gz
         overwrite: true
         tag: ${{ github.ref }}
-        body: ${{ steps.tag.outputs.chglog }}
 
   windows:
     strategy:
